FROM node:16-alpine3.11 as staging
WORKDIR /home/app
COPY . .
RUN npm install

FROM gcr.io/distroless/nodejs:16
WORKDIR /home/app
COPY --from=staging /home/app /home/app
EXPOSE 3000
CMD ["node","node_modules/serve/bin/serve.js","build","-l","3000"]
